### ISSUE TITLE
AXGrid 예제 코드의 일부가 문법 강조가 안됩니다.

### ISSUE THREAD

**Issue by hyunjun19** [axisj/axisj-jsdoc#2]
![image](https://cloud.githubusercontent.com/assets/421863/5576127/182bfa7e-9036-11e4-87aa-53a37f801bd4.png)

**Comment by tom-axisj** [comment]
학수씨가 탭을 다 붙여놨네요. 수정완료

**Comment by hyunjun19** [comment]
:+1:
